include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated_plugin_registrant.dart
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    prefer_const_constructors_in_immutables: warning

linter:
  rules:
    - always_declare_return_types
    - sort_constructors_first               # Ordena constructores antes de otros métodos
    - type_annotate_public_apis              # Exigir tipos explícitos en API públicas
    - always_put_control_body_on_new_line
    - prefer_contains
    - always_use_package_imports
    - use_named_constants
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - use_string_buffers
    - use_late_for_private_fields_and_variables
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - depend_on_referenced_packages
    - deprecated_consistency
    - diagnostic_describe_all_properties
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - no_duplicate_case_values
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - unnecessary_null_aware_assignments
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_this
    - unnecessary_lambdas
    - use_super_parameters
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - prefer_if_elements_to_conditional_expressions
    - prefer_final_fields
    - prefer_is_empty
    - sized_box_for_whitespace
    - avoid_bool_literals_in_conditional_expressions
    - avoid_void_async
    - prefer_for_elements_to_map_fromIterable
    - no_runtimeType_toString
    - avoid_multiple_declarations_per_line
    - prefer_final_locals
    - prefer_final_in_for_each
    - avoid_slow_async_io
    - prefer_spread_collections
    - unnecessary_await_in_return