name: aulago
description: "Aula Virtual UNAMAD - Universidad Nacional Amazónica de Madre de Dios"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.0.2
  flutter_lints: ^6.0.0
  
  # UI & Navigation
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  lucide_icons_flutter: ^3.0.5
  
  # State Management - Riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  file_picker: ^10.2.0
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  responsive_framework: ^1.5.1
  moony_nav_bar: ^1.3.3
  
  # Charts & Graphics
  fl_chart: ^1.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.5.4
  riverpod_generator: ^2.3.9
  freezed: ^3.1.0
  json_serializable: ^6.9.5

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Activos de la aplicación
  assets:
    - assets/images/


  # Fuentes personalizadas (se usará Google Fonts Noto Sans)
  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: fonts/NotoSans-Regular.ttf
  #       - asset: fonts/NotoSans-Bold.ttf
  #         weight: 700
